services:
  api_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENABLE_CRAFT: "true"
    command:
      - /bin/sh
      - -c
      - alembic upgrade head && echo "Starting Onyx Api Server" && uvicorn onyx.main:app --host 0.0.0.0 --port 8080
    depends_on:
      cache:
        condition: service_started
      index:
        condition: service_started
      inference_model_server:
        condition: service_started
      minio:
        condition: service_started
      opensearch:
        condition: service_started
      relational_db:
        condition: service_started
    environment:
      AUTH_TYPE: basic
      CODE_INTERPRETER_BASE_URL: http://code-interpreter:8000
      ENABLE_CRAFT: "true"
      ENABLE_OPENSEARCH_INDEXING_FOR_ONYX: "false"
      FILE_STORE_BACKEND: s3
      MODEL_SERVER_HOST: inference_model_server
      OPENSEARCH_ADMIN_PASSWORD: StrongPassword123!
      OPENSEARCH_HOST: opensearch
      OUTPUTS_TEMPLATE_PATH: /app/onyx/server/features/build/sandbox/kubernetes/docker/templates/outputs
      PERSISTENT_DOCUMENT_STORAGE_PATH: /app/file-system
      POSTGRES_HOST: relational_db
      REDIS_HOST: cache
      S3_AWS_ACCESS_KEY_ID: minioadmin
      S3_AWS_SECRET_ACCESS_KEY: minioadmin
      S3_ENDPOINT_URL: http://minio:9000
      UNSTRUCTURED_API_URL: http://unstructured:8000
      VENV_TEMPLATE_PATH: /app/onyx/server/features/build/sandbox/kubernetes/docker/templates/venv
      VESPA_HOST: index
      WEB_TEMPLATE_PATH: /app/onyx/server/features/build/sandbox/kubernetes/docker/templates/outputs/web
    extra_hosts:
      - host.docker.internal=host-gateway
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - import urllib.request; urllib.request.urlopen('http://localhost:8080/health')
      timeout: 20s
      interval: 30s
      retries: 3
      start_period: 25s
    image: onyxdotapp/onyx-backend:craft-latest
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: api_server_logs
        target: /var/log/onyx
        volume: {}
      - type: volume
        source: file-system
        target: /app/file-system
        volume: {}
  background:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENABLE_CRAFT: "true"
    command:
      - /bin/sh
      - -c
      - |2-
         if [ -f /app/scripts/setup_craft_templates.sh ]; then
          /app/scripts/setup_craft_templates.sh;
        fi && if [ -f /etc/ssl/certs/custom-ca.crt ]; then
          update-ca-certificates;
        fi && /app/scripts/supervisord_entrypoint.sh
    depends_on:
      cache:
        condition: service_started
      index:
        condition: service_started
      indexing_model_server:
        condition: service_started
      inference_model_server:
        condition: service_started
      opensearch:
        condition: service_started
      relational_db:
        condition: service_started
    environment:
      API_SERVER_HOST: api_server
      API_SERVER_PROTOCOL: http
      CODE_INTERPRETER_BASE_URL: http://code-interpreter:8000
      DISCORD_BOT_INVOKE_CHAR: '!'
      DISCORD_BOT_TOKEN: ""
      ENABLE_CRAFT: "true"
      ENABLE_OPENSEARCH_INDEXING_FOR_ONYX: "false"
      FILE_STORE_BACKEND: s3
      INDEXING_MODEL_SERVER_HOST: indexing_model_server
      MODEL_SERVER_HOST: inference_model_server
      OPENSEARCH_ADMIN_PASSWORD: StrongPassword123!
      OPENSEARCH_HOST: opensearch
      OUTPUTS_TEMPLATE_PATH: /app/onyx/server/features/build/sandbox/kubernetes/docker/templates/outputs
      PERSISTENT_DOCUMENT_STORAGE_PATH: /app/file-system
      POSTGRES_HOST: relational_db
      REDIS_HOST: cache
      S3_AWS_ACCESS_KEY_ID: minioadmin
      S3_AWS_SECRET_ACCESS_KEY: minioadmin
      S3_ENDPOINT_URL: http://minio:9000
      UNSTRUCTURED_API_URL: http://unstructured:8000
      VENV_TEMPLATE_PATH: /app/onyx/server/features/build/sandbox/kubernetes/docker/templates/venv
      VESPA_HOST: index
      WEB_TEMPLATE_PATH: /app/onyx/server/features/build/sandbox/kubernetes/docker/templates/outputs/web
    extra_hosts:
      - host.docker.internal=host-gateway
    image: onyxdotapp/onyx-backend:craft-latest
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: background_logs
        target: /var/log/onyx
        volume: {}
      - type: volume
        source: file-system
        target: /app/file-system
        volume: {}
  cache:
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
    image: redis:7.4-alpine
    networks:
      default: null
    restart: unless-stopped
    tmpfs:
      - /data
  code-interpreter:
    command:
      - bash
      - ./entrypoint.sh
      - code-interpreter-api
    image: onyxdotapp/code-interpreter:latest
    networks:
      default: null
    restart: unless-stopped
    user: root
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind: {}
  index:
    environment:
      VESPA_SKIP_UPGRADE_CHECK: "true"
    image: vespaengine/vespa:8.609.39
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: vespa_volume
        target: /opt/vespa/var
        volume: {}
  indexing_model_server:
    build:
      context: ./backend
      dockerfile: Dockerfile.model_server
    command:
      - /bin/sh
      - -c
      - |-
        if [ "" = "True" ] || [ "" = "true" ]; then
          echo 'Skipping service...';
          exit 0;
        else
          exec uvicorn model_server.main:app --host 0.0.0.0 --port 9000;
        fi
    environment:
      INDEXING_ONLY: "True"
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - import urllib.request; urllib.request.urlopen('http://localhost:9000/api/health')
      timeout: 5s
      interval: 20s
      retries: 3
    image: onyxdotapp/onyx-model-server:craft-latest
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: indexing_huggingface_model_cache
        target: /app/.cache/huggingface
        volume: {}
      - type: volume
        source: indexing_model_server_logs
        target: /var/log/onyx
        volume: {}
  inference_model_server:
    build:
      context: ./backend
      dockerfile: Dockerfile.model_server
    command:
      - /bin/sh
      - -c
      - |-
        if [ "" = "True" ] || [ "" = "true" ]; then
          echo 'Skipping service...';
          exit 0;
        else
          exec uvicorn model_server.main:app --host 0.0.0.0 --port 9000;
        fi
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - import urllib.request; urllib.request.urlopen('http://localhost:9000/api/health')
      timeout: 5s
      interval: 20s
      retries: 3
    image: onyxdotapp/onyx-model-server:craft-latest
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: model_cache_huggingface
        target: /app/.cache/huggingface
        volume: {}
      - type: volume
        source: inference_model_server_logs
        target: /var/log/onyx
        volume: {}
  minio:
    command:
      - server
      - /data
      - --console-address
      - :9001
    environment:
      MINIO_DEFAULT_BUCKETS: onyx-file-store-bucket
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      timeout: 20s
      interval: 30s
      retries: 3
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: minio_data
        target: /data
        volume: {}
  nginx:
    command:
      - /bin/sh
      - -c
      - rm -f /etc/nginx/conf.d/default.conf && cp -a /nginx-templates/. /etc/nginx/conf.d/ && sed 's/r$$//' /etc/nginx/conf.d/run-nginx.sh > /tmp/run-nginx.sh && chmod +x /tmp/run-nginx.sh && /tmp/run-nginx.sh app.conf.template
    depends_on:
      api_server:
        condition: service_started
      web_server:
        condition: service_started
    environment:
      DOMAIN: onyx.dev.significa.sk
      NGINX_PROXY_CONNECT_TIMEOUT: "300"
      NGINX_PROXY_READ_TIMEOUT: "300"
      NGINX_PROXY_SEND_TIMEOUT: "300"
    image: nginx:1.25.5-alpine
    labels:
      traefik.enable: "true"
      traefik.http.routers.onyx.entrypoints: websecure
      traefik.http.routers.onyx.priority: "100"
      traefik.http.routers.onyx.rule: Host(`onyx.dev.significa.sk`)
      traefik.http.routers.onyx.service: onyx-svc
      traefik.http.routers.onyx.tls: "true"
      traefik.http.routers.onyx.tls.certresolver: letsencrypt
      traefik.http.services.onyx-svc.loadbalancer.server.port: "80"
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "18080"
        protocol: tcp
      - mode: ingress
        target: 80
        published: "18000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./deployment/data/nginx
        target: /nginx-templates
        read_only: true
        bind: {}
  opensearch:
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: StrongPassword123!
      OPENSEARCH_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    image: opensearchproject/opensearch:3.4.0
    logging:
      driver: json-file
      options:
        max-file: "6"
        max-size: 50m
    networks:
      default: null
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - type: volume
        source: opensearch-data
        target: /usr/share/opensearch/data
        volume: {}
  relational_db:
    command:
      - -c
      - max_connections=250
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:15.2-alpine
    networks:
      default: null
    restart: unless-stopped
    shm_size: "1073741824"
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/postgresql/data
        volume: {}
  unstructured_api:
    container_name: onyx-unstructured-api
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    networks:
      default:
        aliases:
          - unstructured
          - unstructured_api
    restart: unless-stopped
  web_server:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DISABLE_LOGOUT: ""
        NEXT_PUBLIC_DO_NOT_USE_TOGGLE_OFF_DANSWER_POWERED: "false"
        NEXT_PUBLIC_FORGOT_PASSWORD_ENABLED: ""
        NEXT_PUBLIC_THEME: ""
        NODE_OPTIONS: '"--max-old-space-size=4096"'
    depends_on:
      api_server:
        condition: service_started
    environment:
      INTERNAL_URL: http://api_server:8080
    image: onyxdotapp/onyx-web-server:craft-latest
    networks:
      default: null
    restart: unless-stopped
networks:
  default:
    name: onyx_default
volumes:
  api_server_logs:
    name: onyx_api_server_logs
  background_logs:
    name: onyx_background_logs
  db_volume:
    name: onyx_db_volume
  file-system:
    name: onyx_file-system
  indexing_huggingface_model_cache:
    name: onyx_indexing_huggingface_model_cache
  indexing_model_server_logs:
    name: onyx_indexing_model_server_logs
  inference_model_server_logs:
    name: onyx_inference_model_server_logs
  minio_data:
    name: onyx_minio_data
  model_cache_huggingface:
    name: onyx_model_cache_huggingface
  opensearch-data:
    name: onyx_opensearch-data
  vespa_volume:
    name: onyx_vespa_volume
